### ISSUE TITLE
submit_sm malformed packet

### ISSUE THREAD

**Issue by gushome7** [onlinecity/php-smpp#82]
Hi!
Trying to send sms, get this error. Provider told me about malformed packet.
Any ideas?
Thanks a lot

Binding transmitter...
Send PDU         : 41 bytes
 00 00 00 29 00 00 00 02 00 00 00 00 00 00 00 01 43 47 41 52 43 49 41 00 43 67 61 72 2e 33 32 31 00 57 57 57 00 34 00 00 00 
 command_id      : 0x2
 sequence number : 1
Read PDU         : 24 bytes
 00 00 00 18 80 00 00 02 00 00 00 00 00 00 00 01 53 4d 50 50 53 69 6d 00 
 command id      : 0x80000002
 command status  : 0x0 No Error
 sequence number : 1
Binding status  : 0
Send PDU         : 74 bytes
 00 00 00 4a 00 00 00 04 00 00 00 00 00 00 00 02 00 05 00 34 33 32 31 00 01 01 31 31 35 38 37 39 33 38 35 33 00 00 00 00 00 00 00 00 00 00 1a 4d 65 6e 73 61 6a 65 20 64 65 20 70 72 75 65 62 61 20 64 65 20 65 6e 76 3f 6f 00 
 command_id      : 0x4
 sequence number : 2
Read PDU         : 16 bytes
 00 00 00 10 80 00 00 04 00 00 00 45 00 00 00 02 
 command id      : 0x80000004
 command status  : 0x45 submit_sm or submit_multi failed
 sequence number : 2
PHP Fatal error:  Uncaught exception 'SmppException' with message 'submit_sm or submit_multi failed' in /opt/php-smpp/smppclient.class.php:622
Stack trace:
#0 /opt/php-smpp/smppclient.class.php(392): SmppClient->sendCommand(4, '\x00\x05\x004321\x00\x01\x0111587...')
#1 /opt/php-smpp/smppclient.class.php(340): SmppClient->submit_sm(Object(SmppAddress), Object(SmppAddress), 'Mensaje de prue...', NULL, 0)
#2 /opt/php-smpp/testsend.php(33): SmppClient->sendSMS(Object(SmppAddress), Object(SmppAddress), 'Mensaje de prue...')
#3 {main}
  thrown in /opt/php-smpp/smppclient.class.php on line 622

**Comment by dilushan** [comment]
For future readers reason for this submit_sm error is additional 00 character at the end of submit_sm pdu. Remove it from submit_sm function in smppclient.class.php and smsc will accept your request.
